import Head from 'next/head'
import { withSSRContext } from "aws-amplify";
import { GetStaticProps } from 'next';
import { listResources } from '@/src/graphql/queries';
import { ResourceProps } from '../types/types';
import HeroSection from '@/components/home/HeroSection';

export default function Home({ resources }: { resources: ResourceProps[] }) {

  var heroResources = resources.filter(function (item) {
    return item.section === "hero";
  });

  return (
    <>
      <Head>
        <title>MastoInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full px-4 mx-auto space-y-32 max-w-7xl sm:px-6 md:space-y-48">
        <section className="">
          <HeroSection heroResources={heroResources} />
        </section>
        <div>
          <pre>{JSON.stringify(resources, null, 4)}</pre>
        </div>


      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const SSR = withSSRContext();
  const filter = {
    page: { eq: "home" }
  }
  const { data } = await SSR.API.graphql({
    query: listResources,
    variables: { filter }
  });


  const resources: ResourceProps[] = data.listResources.items
  return {
    props: {
      resources
    },
  };
};
