import Head from 'next/head'
import Image from 'next/image'
import { Auth } from "aws-amplify";
import LoadingSpinner from '@/components/utils/LoadingSpinner';


export default function Home() {
  return (
    <>
      <Head>
        <title>MastoInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-2xl text-red-900">
        Musto

        <button
          type="button"

          onClick={() => {
            Auth.signOut();

          }}

          className='px-2 py-2 mt-12 ml-12 text-white bg-red-500 ron'
        >

          <p>Signout</p>
        </button>
        {/* <LoadingSpinner /> */}
      </main>
    </>
  )
}
