import SidebarLayout from "@/components/dashboard/SidebarLayout";
import { PageWithLayout } from "@/types/types";
import Head from "next/head";
import { ReactElement } from "react";

const Assignments: PageWithLayout = ({ }) => {
    return (
        <>
            <Head>
                <title>{`Dashboard | Assignments`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Assignments
        </>
    );
}
Assignments.getLayout = function (page: ReactElement) {
    return (
        <SidebarLayout >
            <main>{page}</main>
        </SidebarLayout>
    )
}
export default Assignments;