import SidebarLayout from "@/components/dashboard/SidebarLayout";
import { UserContext } from "@/contexts/UserContext";
import { getUserWithEnrolledCourses } from "@/src/customGraphql/queries";
import { PageWithLayout } from "@/types/types";
import { API } from "aws-amplify";
import { ReactElement, useCallback, useContext, useEffect, useState } from "react";
import { GetUserWithEnrolledCourseQuery } from '../../../../types/amplifyCodegen/codegenTypes';
import CourseTable from "@/components/dashboard/tables/CourseTable";
import Head from "next/head";


const EnrolledCourses: PageWithLayout = ({ }) => {
    const [courses, setCourses] = useState<GetUserWithEnrolledCourseQuery | undefined>(undefined);
    const userContext = useContext(UserContext);
    console.log('STUDENTCOURSES', courses);


    const fetchCourses = useCallback(async () => {
        if (userContext?.user) {
            const userId = userContext.user.attributes.sub

            try {
                const res = (await API.graphql({
                    query: getUserWithEnrolledCourses,
                    variables: { id: userId },
                    authMode: "AMAZON_COGNITO_USER_POOLS",
                })) as { data: GetUserWithEnrolledCourseQuery };

                setCourses(res.data);
            } catch (error) {

            }
        }
    }, [userContext?.user]);



    useEffect(() => {
        fetchCourses();
    }, [fetchCourses]);


    return (
        <>
            <Head>
                <title>{`${userContext?.user?.attributes.name} | Enrolled Courses`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h2>Enrolled Courses</h2>
            {/* <CourseTable courses={courses} /> */}
            <pre>{JSON.stringify(courses, null, 4)}</pre>
        </>
    );
}

EnrolledCourses.getLayout = function (page: ReactElement) {
    return (
        <SidebarLayout >
            <main>{page}</main>
        </SidebarLayout>
    )
}
export default EnrolledCourses;


