import SidebarLayout from "@/components/dashboard/SidebarLayout";
import { UserContext } from "@/contexts/UserContext";
import { PageWithLayout } from "@/types/types";
import Head from "next/head";
import { ReactElement, useContext } from "react";


const StudentHome: PageWithLayout = ({ }) => {
    const userContext = useContext(UserContext);

    return (
        <>
            <Head>
                <title>{`Dashboard | ${userContext?.user?.attributes.name}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h2 className="text-slate-200 text-lg font-bold tracking-wide">{userContext?.user?.attributes.name}</h2>
                <h3 className="text-slate-400 text-base font-medium tracking-wide">Email: {userContext?.user?.attributes.email}</h3>
                <h3 className="text-slate-400 text-base font-medium tracking-wide">Number: {userContext?.user?.attributes.phone_number}</h3>
            </div>
            <div className="mt-12 space-x-7">
                <button className="bg-indigo-500 text-slate-100 text-sm px-3 py-2 rounded-sm shadow-md hover:text-white hover:bg-indigo-600 transition ease-in-out duration-150">Edit Info</button>
                <button className="bg-red-500 text-slate-100 text-sm px-3 py-2 rounded-sm shadow-md hover:text-white hover:bg-red-600 transition ease-in-out duration-150">Delete user</button>
            </div>
        </>
    );
}

StudentHome.getLayout = function (page: ReactElement) {
    return (
        <SidebarLayout >
            <main>{page}</main>
        </SidebarLayout>
    )
}
export default StudentHome;